version: "3.8"

services:
  server:
    container_name: tinkoff_server
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./db_data:/var/lib/clickhouse/
      - ./db_logs:/var/log/clickhouse-server/
    networks:
      - tinkoff-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 2s
      timeout: 2s
      retries: 16

  client:
    container_name: tinkoff_db_client
    image: yandex/clickhouse-client
    command: ['--host', 'tinkoff_server', '--query', 'select * from system.functions order by name limit 4']
    networks:
      - tinkoff-network
    depends_on:
      server:
        condition: service_healthy

networks:
    tinkoff-network: